# Generated by Django 3.2.15 on 2023-02-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0005_auto_20221205_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='category',
            field=models.CharField(choices=[('researcher_category_0001', 'Investigador Asociado'), ('researcher_category_0002', 'Investigador Emérito'), ('researcher_category_0003', 'Investigador Junior'), ('researcher_category_0004', 'Investigador Senior'), ('researcher_category_0005', 'Sin categoría')], max_length=124, verbose_name='Categoría'),
        ),
    ]
