# Generated by Django 4.2 on 2023-04-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0006_alter_professor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='dedication',
            field=models.CharField(blank=True, choices=[('dedication_0001', 0), ('dedication_0002', 1)], max_length=115, null=True, verbose_name='Dedicación'),
        ),
        migrations.AddField(
            model_name='professor',
            name='index_h',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indice_H'),
        ),
        migrations.AddField(
            model_name='professor',
            name='index_i10',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indice_I10'),
        ),
    ]
