# Generated by Django 4.2 on 2023-05-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("researchers", "0007_professor_dedication_professor_index_h_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professor",
            name="dedication",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dedication_0001", "Docente catedra 0,3"),
                    ("dedication_0002", "Docente catedra 0,4"),
                    ("dedication_0003", "Docente catedra 0,5"),
                    ("dedication_0004", "Docente catedra 0,6"),
                    ("dedication_0005", "Docente catedra 0,7"),
                    ("dedication_0006", "Docente dedicac. exclusiva"),
                    ("dedication_0007", "Docente medio tiempo"),
                    ("dedication_0008", "Docente tiempo completo"),
                ],
                max_length=115,
                null=True,
                verbose_name="Dedicación",
            ),
        ),
    ]
