# Generated by Django 4.2 on 2023-05-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0007_professor_dedication_professor_index_h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='dedication',
            field=models.CharField(blank=True, choices=[('dedication_0001', 'Docente catedra 0,3'), ('dedication_0002', 'Docente catedra 0,4'), ('dedication_0003', 'Docente catedra 0,5'), ('dedication_0004', 'Docente catedra 0,6'), ('dedication_0005', 'Docente catedra 0,7'), ('dedication_0006', 'Docente dedicac. exclusiva'), ('dedication_0007', 'Docente medio tiempo'), ('dedication_0008', 'Docente tiempo completo')], max_length=115, null=True, verbose_name='Dedicación'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='departament',
            field=models.CharField(choices=[('departament_0001', 'Departamento de Administración'), ('departament_0002', 'Departamento de Ciencias Humanas'), ('departament_0003', 'Departamento de Física y Química'), ('departament_0004', 'Departamento de Informática y Computación'), ('departament_0005', 'Departamento de Ingeniería Civil'), ('departament_0006', 'Departamento de Ingeniería Eléctrica, Electrónica y Computación'), ('departament_0007', 'Departamento de Ingeniería Industrial'), ('departament_0008', 'Departamento de Ingeniería Química'), ('departament_0009', 'Departamento de Matemáticas'), ('departament_0010', 'Escuela de Arquitectura y Urbanismo'), ('departament_0011', 'Otro')], max_length=116, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='faculty',
            field=models.CharField(choices=[('faculty_0001', 'Facultad de Administración'), ('faculty_0002', 'Facultad de Ciencias Exactas y Naturales'), ('faculty_0003', 'Facultad de Ingeniería y Arquitectura'), ('faculty_0004', 'Sin Información')], max_length=112, verbose_name='Facultad'),
        ),
    ]
