# Generated by Django 4.2 on 2023-05-17 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("researchers", "0008_alter_professor_dedication"),
        ("researchers", "0008_alter_professor_dedication_and_more"),
    ]

    operations = []
