# Generated by Django 4.2 on 2023-08-28 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Proyecto"},
        ),
    ]
