# Generated by Django 4.2 on 2023-11-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_project_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="id",
        ),
        migrations.AlterField(
            model_name="project",
            name="hermes_cod",
            field=models.BigIntegerField(
                primary_key=True, serialize=False, verbose_name="Código Hermes"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="quipu_cod_0",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Código QUIPU_1"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="quipu_cod_1",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Código QUIPU_2"
            ),
        ),
    ]
