# Generated by Django 4.2 on 2023-08-28 19:56

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JointCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        help_text="Opcional",
                        null=True,
                        upload_to="uploads/calls_join",
                        verbose_name="Imagen de convocatoria",
                    ),
                ),
                (
                    "expiration",
                    models.DateField(
                        help_text="Hasta cuando está abierta la convocatoria",
                        verbose_name="Finalización",
                    ),
                ),
                ("link", models.URLField(verbose_name="Link de referencia")),
                ("title", models.CharField(max_length=1024, verbose_name="Título")),
                (
                    "objective",
                    tinymce.models.HTMLField(max_length=4096, verbose_name="Objetivo"),
                ),
                (
                    "headed",
                    tinymce.models.HTMLField(
                        max_length=4096, verbose_name="Dirigido a"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Oculta la convoctaria de la vista pública",
                        verbose_name="Convocatoria activa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convocatoria conjunta",
                "verbose_name_plural": "Convocatorias conjuntas",
            },
        ),
        migrations.CreateModel(
            name="MincienciasCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        help_text="Opcional",
                        null=True,
                        upload_to="uploads/calls_internal",
                        verbose_name="Imagen de convocatoria",
                    ),
                ),
                (
                    "expiration",
                    models.DateField(
                        help_text="Hasta cuando está abierta la convocatoria",
                        verbose_name="Finalización",
                    ),
                ),
                ("link", models.URLField(verbose_name="Link de referencia")),
                ("title", models.CharField(max_length=1024, verbose_name="Título")),
                (
                    "objective",
                    tinymce.models.HTMLField(max_length=4096, verbose_name="Objetivo"),
                ),
                (
                    "headed",
                    tinymce.models.HTMLField(
                        max_length=4096, verbose_name="Dirigido a"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Oculta la convoctaria de la vista pública",
                        verbose_name="Convocatoria activa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convocatoria de Minciencias",
                "verbose_name_plural": "Convocatorias de Minciencias",
            },
        ),
        migrations.CreateModel(
            name="StudentsCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=1024, verbose_name="Nombre de la convocatoria"
                    ),
                ),
                (
                    "expiration",
                    models.DateField(
                        help_text="Hasta cuando está abierta la convocatoria",
                        verbose_name="Finalización",
                    ),
                ),
                ("funding", models.CharField(max_length=4096, verbose_name="Proyecto")),
                (
                    "supervise",
                    models.CharField(
                        max_length=4096, verbose_name="Profesor responsable"
                    ),
                ),
                (
                    "students",
                    models.IntegerField(
                        help_text="Cantidad de estudiantes en la convocatoria",
                        verbose_name="Estudiantes",
                    ),
                ),
                (
                    "undergraduate",
                    models.BooleanField(verbose_name="Abierta para pregrado"),
                ),
                (
                    "postgraduate",
                    models.BooleanField(verbose_name="Abierta para posgrado"),
                ),
                (
                    "profile",
                    tinymce.models.HTMLField(
                        max_length=4096, verbose_name="Descripción"
                    ),
                ),
                (
                    "time",
                    models.IntegerField(
                        help_text="Horas a la semana",
                        verbose_name="Disponibilidad de tiempo requerida",
                    ),
                ),
                (
                    "economic_stimulus",
                    models.CharField(
                        help_text="ej. 3 pagos de $2.000.000 y uno de $350.000",
                        max_length=4096,
                        verbose_name="Estímulo económico",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        help_text="ej. 3 Meses y 5 días",
                        max_length=1024,
                        verbose_name="Duración de la vinculación",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Oculta la convoctaria de la vista pública",
                        verbose_name="Convocatoria activa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Convocatoria para estudiantes auxiliares",
                "verbose_name_plural": "Convocatorias para estudiantes auxiliares",
            },
        ),
        migrations.AlterModelOptions(
            name="internalcall",
            options={
                "verbose_name": "Convocatoria interna",
                "verbose_name_plural": "Convocatorias internas",
            },
        ),
        migrations.AlterField(
            model_name="internalcall",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Oculta la convoctaria de la vista pública",
                verbose_name="Convocatoria activa",
            ),
        ),
        migrations.AlterField(
            model_name="internalcall",
            name="expiration",
            field=models.DateField(
                help_text="Hasta cuando está abierta la convocatoria",
                verbose_name="Finalización",
            ),
        ),
        migrations.AlterField(
            model_name="internalcall",
            name="image",
            field=models.FileField(
                blank=True,
                help_text="Opcional",
                null=True,
                upload_to="uploads/calls_internal",
                verbose_name="Imagen de convocatoria",
            ),
        ),
        migrations.AlterField(
            model_name="internalcall",
            name="link",
            field=models.URLField(verbose_name="Link de referencia"),
        ),
        migrations.AlterField(
            model_name="internalcall",
            name="title",
            field=models.CharField(max_length=1024, verbose_name="Título"),
        ),
        migrations.CreateModel(
            name="Timeline_JointCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity",
                    models.CharField(max_length=1024, verbose_name="Actividad"),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Opcional",
                        null=True,
                        verbose_name="Fecha de finalización",
                    ),
                ),
                (
                    "joint_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="calls.jointcall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cronograma",
                "verbose_name_plural": "Cronograma",
            },
        ),
        migrations.CreateModel(
            name="Timeline_InternalCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity",
                    models.CharField(max_length=1024, verbose_name="Actividad"),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Opcional",
                        null=True,
                        verbose_name="Fecha de finalización",
                    ),
                ),
                (
                    "joint_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="calls.internalcall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cronograma",
                "verbose_name_plural": "Cronograma",
            },
        ),
        migrations.CreateModel(
            name="TermsOfReference_StudentsCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1024, verbose_name="Nombre del archivo"
                    ),
                ),
                (
                    "terms_of_reference",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/calls_student",
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "joint_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms_of_reference",
                        to="calls.studentscall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Términos de referencia",
                "verbose_name_plural": "Términos de referencia",
            },
        ),
        migrations.CreateModel(
            name="TermsOfReference_JointCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1024, verbose_name="Nombre del archivo"
                    ),
                ),
                (
                    "terms_of_reference",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/calls_student",
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "joint_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms_of_reference",
                        to="calls.jointcall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Términos de referencia",
                "verbose_name_plural": "Términos de referencia",
            },
        ),
        migrations.CreateModel(
            name="TermsOfReference_InternalCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1024, verbose_name="Nombre del archivo"
                    ),
                ),
                (
                    "terms_of_reference",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/calls_internal",
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "joint_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms_of_reference",
                        to="calls.internalcall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Términos de referencia",
                "verbose_name_plural": "Términos de referencia",
            },
        ),
        migrations.CreateModel(
            name="Result_StudentsCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1024, verbose_name="Nombre del archivo"
                    ),
                ),
                (
                    "result",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/calls_student",
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "joint_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="calls.studentscall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado",
            },
        ),
        migrations.CreateModel(
            name="Result_JointCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="name")),
                (
                    "results",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/calls_join",
                        verbose_name="result",
                    ),
                ),
                (
                    "joint_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="calls.jointcall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Result",
            },
        ),
        migrations.CreateModel(
            name="Result_InternalCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1024, verbose_name="Nombre del archivo"
                    ),
                ),
                (
                    "results",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/calls_internal",
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "joint_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="calls.internalcall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado",
            },
        ),
        migrations.CreateModel(
            name="Annex_StudentsCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1024, verbose_name="Nombre del archivo"
                    ),
                ),
                (
                    "annex",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/calls_student",
                        verbose_name="Anexo",
                    ),
                ),
                (
                    "joint_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annex",
                        to="calls.studentscall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo",
            },
        ),
        migrations.CreateModel(
            name="Annex_JointCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1024, verbose_name="Nombre del archivo"
                    ),
                ),
                (
                    "annex",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/calls_student",
                        verbose_name="Anexo",
                    ),
                ),
                (
                    "joint_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annex",
                        to="calls.jointcall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo",
            },
        ),
        migrations.CreateModel(
            name="Annex_InternalCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1024, verbose_name="Nombre del archivo"
                    ),
                ),
                (
                    "annex",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/calls_internal",
                        verbose_name="Anexo",
                    ),
                ),
                (
                    "joint_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annex",
                        to="calls.internalcall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo",
            },
        ),
    ]
