# Generated by Django 4.2 on 2023-08-28 19:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0002_jointcall_mincienciascall_studentscall_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalcall",
            name="headed",
            field=tinymce.models.HTMLField(
                default=" ", max_length=4096, verbose_name="Dirigido a"
            ),
        ),
        migrations.AddField(
            model_name="internalcall",
            name="objective",
            field=tinymce.models.HTMLField(
                default=" ", max_length=4096, verbose_name="Objetivo"
            ),
        ),
    ]
