# Generated by Django 3.2.15 on 2023-02-03 01:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0022_auto_20221205_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscall',
            name='postgraduate',
            field=models.BooleanField(default=True, verbose_name='Abierta para posgrado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentscall',
            name='undergraduate',
            field=models.BooleanField(default=True, verbose_name='Abierta para pregrado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentscall',
            name='funding',
            field=models.CharField(max_length=4096, verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='studentscall',
            name='period',
            field=models.CharField(help_text='ej. 3 Meses y 5 días', max_length=1024, verbose_name='Duración de la vinculación'),
        ),
        migrations.AlterField(
            model_name='studentscall',
            name='profile',
            field=tinymce.models.HTMLField(max_length=4096, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='studentscall',
            name='time',
            field=models.IntegerField(help_text='Horas a la semana', verbose_name='Disponibilidad de tiempo requerida'),
        ),
        migrations.AlterField(
            model_name='studentscall',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Nombre de la convocatoria'),
        ),
    ]
