# Generated by Django 4.2 on 2023-04-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0023_auto_20230202_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annex_internalcall',
            name='annex',
            field=models.FileField(blank=True, null=True, upload_to='uploads\\calls_internal', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='annex_jointcall',
            name='annex',
            field=models.FileField(blank=True, null=True, upload_to='uploads\\calls_student', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='annex_studentscall',
            name='annex',
            field=models.FileField(blank=True, null=True, upload_to='uploads\\calls_student', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='internalcall',
            name='image',
            field=models.FileField(blank=True, help_text='Opcional', null=True, upload_to='uploads\\calls_internal', verbose_name='Imagen de convocatoria'),
        ),
        migrations.AlterField(
            model_name='jointcall',
            name='image',
            field=models.FileField(blank=True, help_text='Opcional', null=True, upload_to='uploads\\calls_join', verbose_name='Imagen de convocatoria'),
        ),
        migrations.AlterField(
            model_name='mincienciascall',
            name='image',
            field=models.FileField(blank=True, help_text='Opcional', null=True, upload_to='uploads\\calls_internal', verbose_name='Imagen de convocatoria'),
        ),
        migrations.AlterField(
            model_name='result_internalcall',
            name='results',
            field=models.FileField(blank=True, null=True, upload_to='uploads\\calls_internal', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='result_jointcall',
            name='results',
            field=models.FileField(blank=True, null=True, upload_to='uploads\\calls_join', verbose_name='result'),
        ),
        migrations.AlterField(
            model_name='result_studentscall',
            name='result',
            field=models.FileField(blank=True, null=True, upload_to='uploads\\calls_student', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='termsofreference_internalcall',
            name='terms_of_reference',
            field=models.FileField(blank=True, null=True, upload_to='uploads\\calls_internal', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='termsofreference_jointcall',
            name='terms_of_reference',
            field=models.FileField(blank=True, null=True, upload_to='uploads\\calls_student', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='termsofreference_studentscall',
            name='terms_of_reference',
            field=models.FileField(blank=True, null=True, upload_to='uploads\\calls_student', verbose_name='Archivo'),
        ),
    ]
