# Generated by Django 3.2.15 on 2023-02-11 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuipuProject',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='Código Quipu')),
                ('proyecto', models.CharField(max_length=32, verbose_name='Nombre del proyecto')),
                ('empresa', models.CharField(max_length=32, verbose_name='Empresa')),
                ('inicio_reporte', models.DateField(verbose_name='Desde')),
                ('fin_reporte', models.DateField(verbose_name='Hasta')),
            ],
        ),
        migrations.CreateModel(
            name='Resources_QuipuProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=32, verbose_name='Recurso')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='quipu.quipuproject')),
            ],
        ),
        migrations.CreateModel(
            name='Row_QuipuProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imputacion', models.CharField(max_length=32, verbose_name='Imputación')),
                ('apropiacion', models.CharField(max_length=32, verbose_name='Apropiación definitiva')),
                ('cupo', models.CharField(max_length=32, verbose_name='Cupo')),
                ('disponibilidad', models.CharField(max_length=32, verbose_name='Disponibilidad')),
                ('registro', models.CharField(max_length=32, verbose_name='Registro')),
                ('obligaciones', models.CharField(max_length=32, verbose_name='Obligaciones')),
                ('pago', models.CharField(max_length=32, verbose_name='Pago')),
                ('saldo_por_comprometer', models.CharField(max_length=32, verbose_name='Saldo por comprometer')),
                ('por_ejecutar', models.CharField(max_length=32, verbose_name='Porcentaje por ejecutar')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='quipu.resources_quipuproject')),
            ],
        ),
    ]
