# Generated by Django 3.2.15 on 2023-02-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quipu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row_quipuproject',
            name='apropiacion',
            field=models.BigIntegerField(verbose_name='Apropiación definitiva'),
        ),
        migrations.AlterField(
            model_name='row_quipuproject',
            name='cupo',
            field=models.BigIntegerField(verbose_name='Cupo'),
        ),
        migrations.AlterField(
            model_name='row_quipuproject',
            name='disponibilidad',
            field=models.BigIntegerField(verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='row_quipuproject',
            name='imputacion',
            field=models.BigIntegerField(verbose_name='Imputación'),
        ),
        migrations.AlterField(
            model_name='row_quipuproject',
            name='obligaciones',
            field=models.BigIntegerField(verbose_name='Obligaciones'),
        ),
        migrations.AlterField(
            model_name='row_quipuproject',
            name='pago',
            field=models.BigIntegerField(verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='row_quipuproject',
            name='por_ejecutar',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Porcentaje por ejecutar'),
        ),
        migrations.AlterField(
            model_name='row_quipuproject',
            name='registro',
            field=models.BigIntegerField(verbose_name='Registro'),
        ),
        migrations.AlterField(
            model_name='row_quipuproject',
            name='saldo_por_comprometer',
            field=models.BigIntegerField(verbose_name='Saldo por comprometer'),
        ),
    ]
