# Generated by Django 3.2.15 on 2023-02-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quipu', '0002_auto_20230210_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row_quipuproject',
            name='por_ejecutar',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje por ejecutar'),
        ),
    ]
