# Generated by Django 4.2 on 2023-05-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quipu', '0003_alter_row_quipuproject_por_ejecutar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quipu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hermes_cod', models.IntegerField(verbose_name='Código Hermes')),
                ('quipu_cod_0', models.IntegerField(blank=True, null=True, verbose_name='Código QUIPU_2')),
                ('project_name', models.CharField(max_length=64, verbose_name='Nombre del Proyecto')),
                ('project_state', models.CharField(choices=[('project_state_0001', 'Activo'), ('project_state_0002', 'Finalizado'), ('project_state_0003', 'No aprobado'), ('project_state_0004', 'Propuesto'), ('project_state_0005', 'Sin finalizar')], max_length=118, verbose_name='Estado del Proyecto')),
                ('call', models.CharField(max_length=64, verbose_name='Convocatoria')),
                ('modality', models.CharField(max_length=64, verbose_name='Modalidad')),
                ('professor_id', models.BigIntegerField(verbose_name='Identificación Investigador')),
                ('first_name', models.CharField(max_length=64, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=64, verbose_name='Apellido(s)')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo del Investigador')),
                ('departament', models.CharField(choices=[('departament_0001', 'Departamento de Administración'), ('departament_0002', 'Departamento de Ciencias Humanas'), ('departament_0003', 'Departamento de Física y Química'), ('departament_0004', 'Departamento de Informática y Computación'), ('departament_0005', 'Departamento de Ingeniería Civil'), ('departament_0006', 'Departamento de Ingeniería Eléctrica, Electrónica y Computación'), ('departament_0007', 'Departamento de Ingeniería Industrial'), ('departament_0008', 'Departamento de Ingeniería Química'), ('departament_0009', 'Departamento de Matemáticas'), ('departament_0010', 'Escuela de Arquitectura y Urbanismo'), ('departament_0011', 'Otro')], max_length=116, verbose_name='Departamento')),
                ('faculty', models.CharField(choices=[('faculty_0001', 'Facultad de Administración'), ('faculty_0002', 'Facultad de Ciencias Exactas y Naturales'), ('faculty_0003', 'Facultad de Ingeniería y Arquitectura'), ('faculty_0004', 'Sin Información')], max_length=112, verbose_name='Facultad')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('total_project', models.IntegerField(blank=True, null=True, verbose_name='Total Proyecto')),
                ('total_appropriation', models.IntegerField(blank=True, null=True, verbose_name='Total Apropiación')),
                ('executed', models.IntegerField(blank=True, null=True, verbose_name='Ejecutado')),
                ('total_commitment_balance', models.IntegerField(blank=True, null=True, verbose_name='Total Saldo por Comprometer')),
                ('execution_percentage', models.FloatField(blank=True, null=True, verbose_name='Porcentaje Ejecutado')),
            ],
            options={
                'verbose_name': 'QUIPU',
            },
        ),
    ]
