# Generated by Django 4.2 on 2023-05-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quipu', '0004_quipu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quipu',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='quipu',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='Apellido(s)'),
        ),
    ]
