# Generated by Django 4.2 on 2023-05-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quipu', '0005_alter_quipu_first_name_alter_quipu_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quipu',
        ),
    ]
