# Generated by Django 4.2 on 2023-08-28 19:56

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        upload_to="uploads/broadcast",
                        verbose_name="Imagen para difusión",
                    ),
                ),
                (
                    "expiration",
                    models.DateField(
                        help_text="Hasta cuando será visible en el carusel",
                        verbose_name="Finalización",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Opcional",
                        null=True,
                        verbose_name="Link de referencia",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Opcional",
                        max_length=1024,
                        null=True,
                        verbose_name="Titulo",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Opcional",
                        max_length=1024,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                ("upload", models.DateTimeField(auto_now_add=True)),
                (
                    "dominant",
                    models.CharField(
                        blank=True, editable=False, max_length=7, null=True
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="La oculta del carusel ",
                        verbose_name="Difusión activa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Difusión (imagen en carusel)",
                "verbose_name_plural": "Difusiónes",
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "label",
                    models.CharField(
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Destino",
                    ),
                ),
                (
                    "content",
                    tinymce.models.HTMLField(
                        max_length=32768, verbose_name="Contenido"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contenido estático",
                "verbose_name_plural": "Contenidos estáticos",
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/newsletter", verbose_name="Boletín"
                    ),
                ),
                ("upload", models.DateTimeField(auto_now_add=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/newsletter"
                    ),
                ),
            ],
            options={
                "verbose_name": "Boletín",
                "verbose_name_plural": "Boletines",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=256, verbose_name="Area")),
                (
                    "names",
                    models.CharField(
                        help_text="Separados por coma (,)",
                        max_length=256,
                        verbose_name="Nombres",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        help_text="Separados por coma (,)",
                        max_length=256,
                        verbose_name="Correos electrónicos",
                    ),
                ),
                (
                    "ext",
                    models.CharField(
                        help_text="Separados por coma (,)",
                        max_length=8,
                        verbose_name="Extensiones",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipo de trabajo",
                "verbose_name_plural": "Equipo de trabajo",
            },
        ),
        migrations.CreateModel(
            name="Attachment_Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1024, verbose_name="Nombre del archivo"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/content",
                        verbose_name="Adjunto",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="Tipo"
                    ),
                ),
                (
                    "size",
                    models.FloatField(blank=True, null=True, verbose_name="Tamaño"),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="Área"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="Etiqueta"
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachment",
                        to="dima.content",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adjunto",
            },
        ),
    ]
