# Generated by Django 4.2 on 2023-11-20 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dima", "0002_updatefiles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="updatefiles",
            options={"verbose_name": "Boletín", "verbose_name_plural": "Boletines"},
        ),
    ]
