# Generated by Django 3.2.15 on 2023-02-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0008_attachment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='label',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Destino'),
        ),
    ]
