# Generated by Django 4.2 on 2023-07-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0015_remove_attachment_content_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment_content',
            name='label',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Etiqueta'),
        ),
    ]
