# Generated by Django 4.2 on 2023-12-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seminars", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seminars",
            name="state",
            field=models.CharField(
                choices=[
                    ("seminar_state_0001", "Activo"),
                    ("seminar_state_0002", "Inactivo"),
                ],
                max_length=118,
                verbose_name="Estado actual",
            ),
        ),
    ]
