# Generated by Django 4.2 on 2023-12-18 14:47

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):
    dependencies = [
        ("seminars", "0002_alter_seminars_state"),
    ]

    operations = [
        UnaccentExtension()
    ]

