# Generated by Django 4.2 on 2023-12-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seminars", "0003_auto_20231218_0947"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seminars",
            name="leader",
            field=models.CharField(default="", max_length=65536, verbose_name="Líder"),
        ),
    ]
