# Generated by Django 4.2 on 2023-12-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seminars", "0004_alter_seminars_leader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seminars",
            name="departament",
            field=models.CharField(
                choices=[
                    ("departament_0001", "Departamento de Administración"),
                    ("departament_0002", "Departamento de Ciencias Humanas"),
                    ("departament_0003", "Departamento de Física y Química"),
                    ("departament_0004", "Departamento de Informática y Computación"),
                    ("departament_0005", "Departamento de Ingeniería Civil"),
                    (
                        "departament_0006",
                        "Departamento de Ingeniería Eléctrica, Electrónica y Computación",
                    ),
                    ("departament_0007", "Departamento de Ingeniería Industrial"),
                    ("departament_0008", "Departamento de Ingeniería Química"),
                    ("departament_0009", "Departamento de Matemáticas"),
                    ("departament_0010", "Escuela de Arquitectura y Urbanismo"),
                    ("departament_0011", "Otro"),
                ],
                max_length=116,
                verbose_name="Departamento",
            ),
        ),
        migrations.AlterField(
            model_name="seminars",
            name="faculty",
            field=models.CharField(
                choices=[
                    ("faculty_0001", "Facultad de Administración"),
                    ("faculty_0002", "Facultad de Ciencias Exactas y Naturales"),
                    ("faculty_0003", "Facultad de Ingeniería y Arquitectura"),
                    ("faculty_0004", "Sin Información"),
                ],
                max_length=112,
                verbose_name="Facultad",
            ),
        ),
    ]
