# Generated by Django 4.2 on 2023-12-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seminars", "0005_alter_seminars_departament_alter_seminars_faculty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seminars",
            name="ocde",
            field=models.CharField(max_length=65536, verbose_name="OCDE"),
        ),
    ]
