# Generated by Django 4.2 on 2023-05-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intellectual_property', '0005_auto_20221205_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='departament',
            field=models.CharField(choices=[('departament_0001', 'Departamento de Administración'), ('departament_0002', 'Departamento de Ciencias Humanas'), ('departament_0003', 'Departamento de Física y Química'), ('departament_0004', 'Departamento de Informática y Computación'), ('departament_0005', 'Departamento de Ingeniería Civil'), ('departament_0006', 'Departamento de Ingeniería Eléctrica, Electrónica y Computación'), ('departament_0007', 'Departamento de Ingeniería Industrial'), ('departament_0008', 'Departamento de Ingeniería Química'), ('departament_0009', 'Departamento de Matemáticas'), ('departament_0010', 'Escuela de Arquitectura y Urbanismo'), ('departament_0011', 'Otro')], max_length=116, verbose_name='Departamento'),
        ),
    ]
