# Generated by Django 4.2 on 2023-08-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intellectual_property", "0006_alter_patent_departament"),
    ]

    operations = [
        migrations.AddField(
            model_name="patent",
            name="faculty",
            field=models.CharField(
                choices=[
                    ("faculty_0001", "Facultad de Administración"),
                    ("faculty_0002", "Facultad de Ciencias Exactas y Naturales"),
                    ("faculty_0003", "Facultad de Ingeniería y Arquitectura"),
                    ("faculty_0004", "Sin Información"),
                ],
                default="nan",
                max_length=112,
                verbose_name="Facultad",
            ),
            preserve_default=False,
        ),
    ]
